[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  directory = "functions"

[build.environment]
  NODE_VERSION = "20"   # ensures build uses Node 20
